import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { Sigil } from "../target/types/sigil";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import { assert, expect } from "chai";
import { createHash } from "crypto";

describe("sigil", () => {
  anchor.setProvider(anchor.AnchorProvider.env());
  const program = anchor.workspace.Sigil as Program<Sigil>;
  const provider = anchor.getProvider() as anchor.AnchorProvider;

  // Test keypairs
  const agent = Keypair.generate();
  const wrongAgent = Keypair.generate();

  // Test proposal ID
  const proposalId = Array.from(Buffer.alloc(32, 1));

  // Dummy proof data (will fail verification — used for error path tests)
  const dummyProofA = Array.from(Buffer.alloc(64, 0));
  const dummyProofB = Array.from(Buffer.alloc(128, 0));
  const dummyProofC = Array.from(Buffer.alloc(64, 0));
  const dummyPublicInputs = Array(5).fill(Array.from(Buffer.alloc(32, 0)));

  // Valid image ID matching SIGIL_V1_IMAGE_ID constant
  const validImageId = (() => {
    const buf = Buffer.alloc(32);
    const words = [357791285, 2944447908, 1179490828, 357895610, 3805270980, 138964069, 3709529647, 1803849831];
    words.forEach((w, i) => buf.writeUInt32LE(w, i * 4));
    return Array.from(buf);
  })();

  const wrongImageId = Array.from(Buffer.alloc(32, 99));

  // Empty journal bytes (error path tests hit checks 1-3 before journal decode)
  const emptyJournal = Buffer.alloc(0);

  // ── REAL GROTH16 PROOF DATA ─────────────────────────────────────────────────
  // Generated by scoring-function/host with a TreasurySpend proposal.
  // Score: 88, Position: 0 (PASS)

  const realProofA = Array.from(Buffer.from(
    "10c92d20964ac630f05f65ba161f46eb06147c1fb3fa5ab33fc43b57ba7174350d6bedc623b12426eae8da7dd972dde6f077e68ee251ad174528c1107d530680",
    "hex"
  ));
  const realProofB = Array.from(Buffer.from(
    "115fbaf9e1e01e2826a4692c04cac4f4259a2914d7ee1e50d4183340b1cc028d076181b24ea9b2141afdfd251ea8b23ed24ade69b3ea9cd9e76d8742e552df5907d0c64f979cd3edb07226cdc20e1405e56d8367387496b7ae38790ce54febed2cea3f5d171f9eff2b6c55f81e7a26855f5228a6a45201f7455cdb55be9abe3c",
    "hex"
  ));
  const realProofC = Array.from(Buffer.from(
    "28833c9935512ea02cdc62bc16647129ac4e5e00f5e53888da8da5f57536e6ad27801624441c4df4f3885bb8f90bb50150474c4f2c8335f9fab1ccc19e556b7d",
    "hex"
  ));
  const realPublicInputs = [
    Array.from(Buffer.from("0000000000000000000000000000000041af18736dc9d7921c859fc95ac84da5", "hex")),
    Array.from(Buffer.from("00000000000000000000000000000000561f8c992a424deb37ccdf4e19c0e7db", "hex")),
    Array.from(Buffer.from("00000000000000000000000000000000d03334f01a4fc05714e1f5c1ab300b33", "hex")),
    Array.from(Buffer.from("00000000000000000000000000000000ee3f347f039cbf82fcd698e226b623ea", "hex")),
    Array.from(Buffer.from("04446e66d300eb7fb45c9726bb53c793dda407a62e9601618bb43c5c14657ac0", "hex")),
  ];

  // Expected claim_digest reconstructed from public_inputs[2..3]:
  // pi_high[16..32] || pi_low[16..32]
  const expectedClaimDigest = Buffer.from(
    "ee3f347f039cbf82fcd698e226b623ead03334f01a4fc05714e1f5c1ab300b33",
    "hex"
  );

  // ── HELPERS ─────────────────────────────────────────────────────────────────

  // Build journal bytes in risc0 word-aligned format:
  // each u8 → u32 LE word (4 bytes), u32 → u32 LE word (4 bytes)
  function buildJournalBytes(
    agentPubkey: Buffer,
    propId: number[],
    position: number,
    score: number
  ): Buffer {
    const buf = Buffer.alloc(264);
    for (let i = 0; i < 32; i++) {
      buf.writeUInt32LE(agentPubkey[i], i * 4);
    }
    for (let i = 0; i < 32; i++) {
      buf.writeUInt32LE(propId[i], 128 + i * 4);
    }
    buf.writeUInt32LE(position, 256);
    buf.writeUInt32LE(score, 260);
    return buf;
  }

  function sha256(data: Buffer): Buffer {
    return createHash("sha256").update(data).digest();
  }

  function getReceiptPda(agentKey: PublicKey, propId: number[]): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("sigil"),
        Buffer.from("v1"),
        Buffer.from("receipt"),
        agentKey.toBuffer(),
        Buffer.from(propId),
      ],
      program.programId
    );
  }

  async function airdrop(key: PublicKey) {
    const sig = await provider.connection.requestAirdrop(key, 10 * anchor.web3.LAMPORTS_PER_SOL);
    await provider.connection.confirmTransaction(sig);
  }

  before(async () => {
    await airdrop(agent.publicKey);
    await airdrop(wrongAgent.publicKey);
  });

  // ── ERROR PATH TESTS ──────────────────────────────────────────────────────

  it("Rejects invalid image ID", async () => {
    const [receipt] = getReceiptPda(agent.publicKey, proposalId);
    try {
      await program.methods
        .issueVerifiedReceipt(
          proposalId,
          dummyProofA, dummyProofB, dummyProofC,
          dummyPublicInputs,
          wrongImageId,
          emptyJournal,
          0
        )
        .accounts({
          agent: agent.publicKey,
          receipt,
          systemProgram: SystemProgram.programId,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown InvalidImageId");
    } catch (err: any) {
      expect(err.error?.errorCode?.code).to.equal("InvalidImageId");
    }
  });

  it("Rejects invalid position (> 1)", async () => {
    const [receipt] = getReceiptPda(agent.publicKey, proposalId);
    try {
      await program.methods
        .issueVerifiedReceipt(
          proposalId,
          dummyProofA, dummyProofB, dummyProofC,
          dummyPublicInputs,
          validImageId,
          emptyJournal,
          2
        )
        .accounts({
          agent: agent.publicKey,
          receipt,
          systemProgram: SystemProgram.programId,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown InvalidPosition");
    } catch (err: any) {
      expect(err.error?.errorCode?.code).to.equal("InvalidPosition");
    }
  });

  it("Rejects bad Groth16 proof", async () => {
    const [receipt] = getReceiptPda(agent.publicKey, proposalId);
    try {
      await program.methods
        .issueVerifiedReceipt(
          proposalId,
          dummyProofA, dummyProofB, dummyProofC,
          dummyPublicInputs,
          validImageId,
          emptyJournal,
          0
        )
        .accounts({
          agent: agent.publicKey,
          receipt,
          systemProgram: SystemProgram.programId,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown ProofVerificationFailed");
    } catch (err: any) {
      expect(err.error?.errorCode?.code).to.equal("ProofVerificationFailed");
    }
  });

  // ── HAPPY PATH: FULL LIFECYCLE ────────────────────────────────────────────

  // Use a separate proposal ID for the happy path to avoid PDA conflicts
  const happyProposalId = Array.from(Buffer.alloc(32, 2));
  const happyPosition = 0; // PASS
  const happyScore = 88;

  it("Issues a verified receipt with real Groth16 proof", async () => {
    const journalBytes = buildJournalBytes(
      agent.publicKey.toBuffer(),
      happyProposalId,
      happyPosition,
      happyScore
    );
    const expectedJournalDigest = sha256(journalBytes);

    const [receipt] = getReceiptPda(agent.publicKey, happyProposalId);

    await program.methods
      .issueVerifiedReceipt(
        happyProposalId,
        realProofA, realProofB, realProofC,
        realPublicInputs,
        validImageId,
        journalBytes,
        happyPosition
      )
      .accounts({
        agent: agent.publicKey,
        receipt,
        systemProgram: SystemProgram.programId,
      })
      .signers([agent])
      .rpc();

    // Fetch and verify the receipt account
    const receiptAccount = await program.account.verifiedComputeReceipt.fetch(receipt);

    assert(
      receiptAccount.agent.equals(agent.publicKey),
      "agent should match signer"
    );
    expect(receiptAccount.position).to.equal(happyPosition);
    expect(receiptAccount.proofType).to.equal(0); // ZK_ARITHMETIC
    expect(receiptAccount.isSettled).to.equal(false);
    assert.deepEqual(
      receiptAccount.proposalId,
      happyProposalId,
      "proposal_id should match"
    );
    assert.deepEqual(
      receiptAccount.imageId,
      validImageId,
      "image_id should match"
    );
    assert.deepEqual(
      Array.from(Buffer.from(receiptAccount.journalDigest)),
      Array.from(expectedJournalDigest),
      "journal_digest should be SHA-256 of journal bytes"
    );
    assert.deepEqual(
      Array.from(Buffer.from(receiptAccount.claimDigest)),
      Array.from(expectedClaimDigest),
      "claim_digest should be reconstructed from public_inputs[2..3]"
    );

    // receipt_hash should be non-zero
    const receiptHash = Buffer.from(receiptAccount.receiptHash);
    assert(
      !receiptHash.equals(Buffer.alloc(32, 0)),
      "receipt_hash should be non-zero"
    );
  });

  it("Marks receipt as settled", async () => {
    const [receipt] = getReceiptPda(agent.publicKey, happyProposalId);

    await program.methods
      .markSettled()
      .accounts({
        agent: agent.publicKey,
        receipt,
      })
      .signers([agent])
      .rpc();

    const receiptAccount = await program.account.verifiedComputeReceipt.fetch(receipt);
    expect(receiptAccount.isSettled).to.equal(true);
  });

  it("Closes receipt and reclaims rent", async () => {
    const [receipt] = getReceiptPda(agent.publicKey, happyProposalId);

    const balanceBefore = await provider.connection.getBalance(agent.publicKey);

    await program.methods
      .closeReceipt()
      .accounts({
        agent: agent.publicKey,
        receipt,
      })
      .signers([agent])
      .rpc();

    // Account should no longer exist
    const accountInfo = await provider.connection.getAccountInfo(receipt);
    assert.isNull(accountInfo, "receipt account should be closed");

    // Agent should have received rent back
    const balanceAfter = await provider.connection.getBalance(agent.publicKey);
    assert(
      balanceAfter > balanceBefore,
      "agent balance should increase after rent reclaim"
    );
  });

  // ── CONSTRAINT TESTS (now with real receipt) ──────────────────────────────

  it("Prevents mark_settled by wrong agent", async () => {
    const [receipt] = getReceiptPda(agent.publicKey, proposalId);
    try {
      await program.methods
        .markSettled()
        .accounts({
          agent: wrongAgent.publicKey,
          receipt,
        })
        .signers([wrongAgent])
        .rpc();
      assert.fail("Should have thrown UnauthorizedAgent");
    } catch (err: any) {
      const isUnauthorized = err.error?.errorCode?.code === "UnauthorizedAgent";
      const isAccountNotFound = err.message?.includes("Account does not exist") || err.error?.errorCode?.code === "AccountNotInitialized";
      assert(isUnauthorized || isAccountNotFound, `Unexpected error: ${err.message}`);
    }
  });

  it("Prevents close_receipt before settlement", async () => {
    const [receipt] = getReceiptPda(agent.publicKey, proposalId);
    try {
      await program.methods
        .closeReceipt()
        .accounts({
          agent: agent.publicKey,
          receipt,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown NotYetSettled");
    } catch (err: any) {
      const isNotSettled = err.error?.errorCode?.code === "NotYetSettled";
      const isAccountNotFound = err.message?.includes("Account does not exist") || err.error?.errorCode?.code === "AccountNotInitialized";
      assert(isNotSettled || isAccountNotFound, `Unexpected error: ${err.message}`);
    }
  });

  // ── PDA DETERMINISM TESTS ─────────────────────────────────────────────────

  it("PDA is deterministic — same agent and proposal always produce same address", () => {
    const [pda1] = getReceiptPda(agent.publicKey, proposalId);
    const [pda2] = getReceiptPda(agent.publicKey, proposalId);
    const [pda3] = getReceiptPda(wrongAgent.publicKey, proposalId);
    assert(pda1.equals(pda2), "Same inputs should produce same PDA");
    assert(!pda1.equals(pda3), "Different agents should produce different PDAs");
  });

  it("Different proposal IDs produce different PDAs", () => {
    const proposalId2 = Array.from(Buffer.alloc(32, 2));
    const [pda1] = getReceiptPda(agent.publicKey, proposalId);
    const [pda2] = getReceiptPda(agent.publicKey, proposalId2);
    assert(!pda1.equals(pda2), "Different proposals should produce different PDAs");
  });
});
